# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'apiaccess-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for apiaccess-ios
  pod 'Alamofire', '~> 4.8.2'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod "JWT", '1.1.3'
  pod 'CryptoSwift', '~> 1.0'

  target 'apiaccess-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'apiaccess-iosUITests' do
    # Pods for testing
  end

end
